### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wjjwkwindy** [wjjwkwindy/get-public-ip#1]
- [ ] make butterUptimeHeartbeats optional
- [ ] add log file name to config
- [ ] auto generate log file if it's not exist
- [ ] auto change tencent firewall when ip changed
